version: "3.9"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
     - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - 7800:7800
    networks:
      - backnet
      - frontnet

  qa-api:
    build:
      context: qa-api
      dockerfile: Dockerfile.prod
    image: qa-api-prod
    volumes:
      - ./qa-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'
    networks:
      - backnet
      - frontnet

  qa-ui:
    build:
      context: qa-ui
      dockerfile: Dockerfile.prod
    image: qa-ui-prod
    ports:
      - 3000:80
    depends_on:
      - qa-api
    volumes:
      - ./qa-ui/:/app
      - astro_node_modules:/app/node_modules
    env_file:
      - project.env
    environment:
      - VITE_QA_URL=/api
      - VITE_LLM_URL=/llm/
    deploy:
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'
    networks:
      - backnet
      - frontnet
  
  llm-api:
    build:
      context: llm-api
      dockerfile: Dockerfile.prod
    image: llm-api-prod
    expose:
      - 7000
    volumes:
      - ./llm-api/:/app
      - ./app-cache/:/app-cache
    deploy:
      restart_policy:
        condition: on-failure
        delay: '5s'
        max_attempts: 5
        window: '30s'
    networks:
      - backnet
      - frontnet

  database:
    container_name: database-server-dab-p2-b7c7d0d1-d2ff-4ef4-9553-e95ea3225629
    image: postgres:14.1
    restart: "unless-stopped"
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - project.env
    networks:
      - backnet
   
  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    networks:
      - backnet
  
  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: on-failure
    env_file:
      - project.env
    depends_on:
      - database
    networks:
      - backnet

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    networks:
      - backnet
  
  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
      

volumes:
  astro_node_modules:

networks:
  backnet:
  frontnet: