version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - 7800:7800

  qa-api:
    build:
      context: qa-api
      dockerfile: Dockerfile
    image: qa-api
    restart: 'no'
    volumes:
      - ./qa-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    networks:
      - backnet
      - frontnet
    deploy:
      replicas: 5

  qa-ui:
    build:
      context: qa-ui
      dockerfile: Dockerfile
    image: qa-ui
    restart: 'no'
    volumes:
      - ./qa-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - qa-api
    networks:
      - backnet
      - frontnet
      
  llm-api:
    build:
      context: llm-api
      dockerfile: Dockerfile
    image: llm-api
    restart: 'no'
    expose:
      - 7000
    volumes:
      - ./llm-api/:/app
      - ./app-cache/:/app-cache
    networks:
      - backnet

  database:
    container_name: database-server-dab-p2-b7c7d0d1-d2ff-4ef4-9553-e95ea3225629
    image: postgres:14.1
    restart: 'no'
    env_file:
      - project.env
    networks:
      - backnet
    environment:
      - TZ="Europe/Helsinki"

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    networks:
      - backnet

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    networks:
      - backnet

  e2e-playwright:
    entrypoint: '/bin/true'
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
      
volumes:
  astro_node_modules:

networks:
  backnet:
  frontnet:
