### get courses
GET http://localhost:7800/api/courses HTTP/1.1


### get questions
GET http://localhost:7800/api/questions HTTP/1.1

### get answers
GET http://localhost:7800/api/answers HTTP/1.1


### get all questions votes
GET http://localhost:7800/api/votes/question HTTP/1.1

### get all answers votes
GET http://localhost:7800/api/votes/answer HTTP/1.1

### get/generate user uuid
GET http://localhost:7800/api/user/uuid HTTP/1.1

### post new question with courseId params
POST http://localhost:7800/api/questions/3 HTTP/1.1
Content-Type: application/json

{
    "user_uuid": "c6fdc5f4-afda-4cf4-b9e9-95b7f2951e42",
    "title": "Sample Question Fortran",
    "details": "Sample details fortran"
}

### post new answer with courseId params and question_id search params
POST http://localhost:7800/api/answers/2?question_id=1 HTTP/1.1
Content-Type: application/json

{
    "user_uuid": "c6fdc5f4-afda-4cf4-b9e9-95b7f2951e42",
    "details": "Sample details fortran"
}

### add new question vote
POST http://localhost:7800/api/vote/question?question_id=1 HTTP/1.1
Content-Type: application/json

{
    "user_uuid": "c6fdc5f4-afda-4cf4-b9e9-95b7f2951e42"
}

### add new answer vote
POST http://localhost:7800/api/vote/answer?answer_id=1 HTTP/1.1
Content-Type: application/json

{
    "user_uuid": "c6fdc5f4-afda-4cf4-b9e9-95b7f2951e42"
}

### generate LLM answers
POST http://localhost:7800/llm/ HTTP/1.1
Content-Type: application/json

{
    "question": "How to write Hello, world! in Fortran?"
}

### update question withautomatedanswer with questionId param
PATCH http://localhost:7800/api/question/2 HTTP/1.1
Content-Type: application/json

{
    "withautomatedanswer": true
    
}

### update question vote with questionId params
PATCH http://localhost:7800/api/question/votes/2 HTTP/1.1
Content-Type: application/json

{
    "votes": 3
    
}

### update answer vote with answerId params
PATCH http://localhost:7800/api/answer/votes/2 HTTP/1.1
Content-Type: application/json

{
    "votes": 2
    
}

######################################
## Dockerize and in K8s

#### all courses dockerize
GET http://localhost:7777/courses HTTP/1.1


### LLM Get request
GET http://127.0.0.1:7001 HTTP/1.1


### generate LLM answers dockerize
POST http://127.0.0.1:7001/ HTTP/1.1
Content-Type: application/json

{
    "question": "How to write Hello, world! in Fortran?"
}



