apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-api-deployment
  labels:
    app: qa-api
spec:
  selector:
    matchLabels:
      app: qa-api
  template:
    metadata:
      labels:
        app: qa-api
    spec:
      containers:
        - name: qa-api
          image: aiotrope/qa-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
          resources:
            requests: 
              cpu: 100m
            limits: 
              cpu: 200m
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: pghost
                  optional: false
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: pguser
                  optional: false
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: pgpassword
                  optional: false
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: pgdatabase
                  optional: false
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: pgport
                  optional: false
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: redisurl
                  optional: false


# The following configuration adds a resource request for 200m CPU units per container (0.2 CPU units) and limits the
# resource usage to 500m CPU units per container (0.5 CPU units).
# modification essentially adds an environment variable called PGPASS to the application.