apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-ui-deployment
  labels:
    app: qa-ui
spec:
  selector:
    matchLabels:
      app: qa-ui
  template:
    metadata:
      labels:
        app: qa-ui
    spec:
      containers:
        - name: qa-ui
          image: aiotrope/qa-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests: 
              cpu: 100m
            limits: 
              cpu: 200m
          env:
            - name: VITE_QA_URL
              value: "http://127.0.0.1:7777"
            - name: VITE_LLM_URL
              value: "http://127.0.0.1:7001"

         

# The following configuration adds a resource request for 100m CPU units per container (0.1 CPU units) and limits the
# resource usage to 200m CPU units per container (0.2 CPU units).